//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Xilium.CefGlue.Interop;
    
    // Role: PROXY
    public unsafe partial class CefSettingObserver : IDisposable
    {
        internal static CefSettingObserver FromNative(cef_setting_observer_t* ptr)
        {
            return new CefSettingObserver(ptr);
        }
        
        internal static CefSettingObserver FromNativeOrNull(cef_setting_observer_t* ptr)
        {
            if (ptr == null) return null;
            return new CefSettingObserver(ptr);
        }
        
        private protected cef_setting_observer_t* _self;
        private protected int _disposed = 0;
        
        private protected CefSettingObserver(cef_setting_observer_t* ptr)
        {
            if (ptr == null) throw new ArgumentNullException("ptr");
            _self = ptr;
            CefObjectTracker.Track(this);
        }
        
        ~CefSettingObserver()
        {
            if (Interlocked.CompareExchange(ref _disposed, 1, 0) == 0)
            {
                Release();
                _self = null;
            }
        }
        
        public void Dispose()
        {
            if (Interlocked.CompareExchange(ref _disposed, 1, 0) == 0)
            {
                Release();
                _self = null;
            }
            CefObjectTracker.Untrack(this);
            GC.SuppressFinalize(this);
        }
        
        internal void AddRef()
        {
            cef_setting_observer_t.add_ref(_self);
        }
        
        internal bool Release()
        {
            return cef_setting_observer_t.release(_self) != 0;
        }
        
        internal bool HasOneRef
        {
            get { return cef_setting_observer_t.has_one_ref(_self) != 0; }
        }
        
        internal bool HasAtLeastOneRef
        {
            get { return cef_setting_observer_t.has_at_least_one_ref(_self) != 0; }
        }
        
        internal cef_setting_observer_t* ToNative()
        {
            AddRef();
            return _self;
        }
    }
}
