//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using Xilium.CefGlue.Interop;
    
    // Role: PROXY
    public sealed unsafe partial class CefSslCertPrincipal : IDisposable
    {
        internal static CefSslCertPrincipal FromNative(cef_sslcert_principal_t* ptr)
        {
            return new CefSslCertPrincipal(ptr);
        }
        
        internal static CefSslCertPrincipal FromNativeOrNull(cef_sslcert_principal_t* ptr)
        {
            if (ptr == null) return null;
            return new CefSslCertPrincipal(ptr);
        }
        
        private cef_sslcert_principal_t* _self;
        
        private CefSslCertPrincipal(cef_sslcert_principal_t* ptr)
        {
            if (ptr == null) throw new ArgumentNullException("ptr");
            _self = ptr;
        }
        
        ~CefSslCertPrincipal()
        {
            if (_self != null)
            {
                Release();
                _self = null;
            }
        }
        
        public void Dispose()
        {
            if (_self != null)
            {
                Release();
                _self = null;
            }
            GC.SuppressFinalize(this);
        }
        
        internal void AddRef()
        {
            cef_sslcert_principal_t.add_ref(_self);
        }
        
        internal bool Release()
        {
            return cef_sslcert_principal_t.release(_self) != 0;
        }
        
        internal bool HasOneRef
        {
            get { return cef_sslcert_principal_t.has_one_ref(_self) != 0; }
        }
        
        internal cef_sslcert_principal_t* ToNative()
        {
            AddRef();
            return _self;
        }
    }
}
