//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using Xilium.CefGlue.Interop;
    
    // Role: HANDLER
    public abstract unsafe partial class CefDomEventListener
    {
        private static Dictionary<IntPtr, CefDomEventListener> _roots = new Dictionary<IntPtr, CefDomEventListener>();
        
        private int _refct;
        private cef_domevent_listener_t* _self;
        
        protected object SyncRoot { get { return this; } }
        
        private cef_domevent_listener_t.add_ref_delegate _ds0;
        private cef_domevent_listener_t.release_delegate _ds1;
        private cef_domevent_listener_t.get_refct_delegate _ds2;
        private cef_domevent_listener_t.handle_event_delegate _ds3;
        
        protected CefDomEventListener()
        {
            _self = cef_domevent_listener_t.Alloc();
        
            _ds0 = new cef_domevent_listener_t.add_ref_delegate(add_ref);
            _self->_base._add_ref = Marshal.GetFunctionPointerForDelegate(_ds0);
            _ds1 = new cef_domevent_listener_t.release_delegate(release);
            _self->_base._release = Marshal.GetFunctionPointerForDelegate(_ds1);
            _ds2 = new cef_domevent_listener_t.get_refct_delegate(get_refct);
            _self->_base._get_refct = Marshal.GetFunctionPointerForDelegate(_ds2);
            _ds3 = new cef_domevent_listener_t.handle_event_delegate(handle_event);
            _self->_handle_event = Marshal.GetFunctionPointerForDelegate(_ds3);
        }
        
        ~CefDomEventListener()
        {
            Dispose(false);
        }
        
        protected virtual void Dispose(bool disposing)
        {
            if (_self != null)
            {
                cef_domevent_listener_t.Free(_self);
                _self = null;
            }
        }
        
        private int add_ref(cef_domevent_listener_t* self)
        {
            lock (SyncRoot)
            {
                var result = ++_refct;
                if (result == 1)
                {
                    lock (_roots) { _roots.Add((IntPtr)_self, this); }
                }
                return result;
            }
        }
        
        private int release(cef_domevent_listener_t* self)
        {
            lock (SyncRoot)
            {
                var result = --_refct;
                if (result == 0)
                {
                    lock (_roots) { _roots.Remove((IntPtr)_self); }
                }
                return result;
            }
        }
        
        private int get_refct(cef_domevent_listener_t* self)
        {
            return _refct;
        }
        
        internal cef_domevent_listener_t* ToNative()
        {
            add_ref(_self);
            return _self;
        }
        
        [Conditional("DEBUG")]
        private void CheckSelf(cef_domevent_listener_t* self)
        {
            if (_self != self) throw ExceptionBuilder.InvalidSelfReference();
        }
        
    }
}
