//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.InteropServices;
    using System.Security;
    
    [StructLayout(LayoutKind.Sequential, Pack = libcef.ALIGN)]
    [SuppressMessage("Microsoft.Design", "CA1049:TypesThatOwnNativeResourcesShouldBeDisposable")]
    internal unsafe struct cef_command_handler_t
    {
        internal cef_base_ref_counted_t _base;
        internal IntPtr _on_chrome_command;
        internal IntPtr _is_chrome_app_menu_item_visible;
        internal IntPtr _is_chrome_app_menu_item_enabled;
        internal IntPtr _is_chrome_page_action_icon_visible;
        internal IntPtr _is_chrome_toolbar_button_visible;
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void add_ref_delegate(cef_command_handler_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int release_delegate(cef_command_handler_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int has_one_ref_delegate(cef_command_handler_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int has_at_least_one_ref_delegate(cef_command_handler_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int on_chrome_command_delegate(cef_command_handler_t* self, cef_browser_t* browser, int command_id, CefWindowOpenDisposition disposition);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int is_chrome_app_menu_item_visible_delegate(cef_command_handler_t* self, cef_browser_t* browser, int command_id);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int is_chrome_app_menu_item_enabled_delegate(cef_command_handler_t* self, cef_browser_t* browser, int command_id);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int is_chrome_page_action_icon_visible_delegate(cef_command_handler_t* self, CefChromePageActionIconType icon_type);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int is_chrome_toolbar_button_visible_delegate(cef_command_handler_t* self, CefChromeToolbarButtonType button_type);
        
        private static int _sizeof;
        
        static cef_command_handler_t()
        {
            _sizeof = Marshal.SizeOf(typeof(cef_command_handler_t));
        }
        
        internal static cef_command_handler_t* Alloc()
        {
            var ptr = (cef_command_handler_t*)Marshal.AllocHGlobal(_sizeof);
            *ptr = new cef_command_handler_t();
            ptr->_base._size = (UIntPtr)_sizeof;
            return ptr;
        }
        
        internal static void Free(cef_command_handler_t* ptr)
        {
            Marshal.FreeHGlobal((IntPtr)ptr);
        }
        
    }
}
