//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.InteropServices;
    using System.Security;
    
    [StructLayout(LayoutKind.Sequential, Pack = libcef.ALIGN)]
    [SuppressMessage("Microsoft.Design", "CA1049:TypesThatOwnNativeResourcesShouldBeDisposable")]
    internal unsafe struct cef_task_manager_t
    {
        internal cef_base_ref_counted_t _base;
        internal IntPtr _get_tasks_count;
        internal IntPtr _get_task_ids_list;
        internal IntPtr _get_task_info;
        internal IntPtr _kill_task;
        internal IntPtr _get_task_id_for_browser_id;
        
        // GetTaskManager
        [DllImport(libcef.DllName, EntryPoint = "cef_task_manager_get", CallingConvention = libcef.CEF_CALL)]
        public static extern cef_task_manager_t* get();
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void add_ref_delegate(cef_task_manager_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int release_delegate(cef_task_manager_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int has_one_ref_delegate(cef_task_manager_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int has_at_least_one_ref_delegate(cef_task_manager_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate UIntPtr get_tasks_count_delegate(cef_task_manager_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int get_task_ids_list_delegate(cef_task_manager_t* self, UIntPtr* task_idsCount, long* task_ids);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int get_task_info_delegate(cef_task_manager_t* self, long task_id, CefTaskInfo* info);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int kill_task_delegate(cef_task_manager_t* self, long task_id);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate long get_task_id_for_browser_id_delegate(cef_task_manager_t* self, int browser_id);
        
        // AddRef
        private static IntPtr _p0;
        private static add_ref_delegate _d0;
        
        public static void add_ref(cef_task_manager_t* self)
        {
            add_ref_delegate d;
            var p = self->_base._add_ref;
            if (p == _p0) { d = _d0; }
            else
            {
                d = (add_ref_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(add_ref_delegate));
                if (_p0 == IntPtr.Zero) { _d0 = d; _p0 = p; }
            }
            d(self);
        }
        
        // Release
        private static IntPtr _p1;
        private static release_delegate _d1;
        
        public static int release(cef_task_manager_t* self)
        {
            release_delegate d;
            var p = self->_base._release;
            if (p == _p1) { d = _d1; }
            else
            {
                d = (release_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(release_delegate));
                if (_p1 == IntPtr.Zero) { _d1 = d; _p1 = p; }
            }
            return d(self);
        }
        
        // HasOneRef
        private static IntPtr _p2;
        private static has_one_ref_delegate _d2;
        
        public static int has_one_ref(cef_task_manager_t* self)
        {
            has_one_ref_delegate d;
            var p = self->_base._has_one_ref;
            if (p == _p2) { d = _d2; }
            else
            {
                d = (has_one_ref_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(has_one_ref_delegate));
                if (_p2 == IntPtr.Zero) { _d2 = d; _p2 = p; }
            }
            return d(self);
        }
        
        // HasAtLeastOneRef
        private static IntPtr _p3;
        private static has_at_least_one_ref_delegate _d3;
        
        public static int has_at_least_one_ref(cef_task_manager_t* self)
        {
            has_at_least_one_ref_delegate d;
            var p = self->_base._has_at_least_one_ref;
            if (p == _p3) { d = _d3; }
            else
            {
                d = (has_at_least_one_ref_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(has_at_least_one_ref_delegate));
                if (_p3 == IntPtr.Zero) { _d3 = d; _p3 = p; }
            }
            return d(self);
        }
        
        // GetTasksCount
        private static IntPtr _p4;
        private static get_tasks_count_delegate _d4;
        
        public static UIntPtr get_tasks_count(cef_task_manager_t* self)
        {
            get_tasks_count_delegate d;
            var p = self->_get_tasks_count;
            if (p == _p4) { d = _d4; }
            else
            {
                d = (get_tasks_count_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_tasks_count_delegate));
                if (_p4 == IntPtr.Zero) { _d4 = d; _p4 = p; }
            }
            return d(self);
        }
        
        // GetTaskIdsList
        private static IntPtr _p5;
        private static get_task_ids_list_delegate _d5;
        
        public static int get_task_ids_list(cef_task_manager_t* self, UIntPtr* task_idsCount, long* task_ids)
        {
            get_task_ids_list_delegate d;
            var p = self->_get_task_ids_list;
            if (p == _p5) { d = _d5; }
            else
            {
                d = (get_task_ids_list_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_task_ids_list_delegate));
                if (_p5 == IntPtr.Zero) { _d5 = d; _p5 = p; }
            }
            return d(self, task_idsCount, task_ids);
        }
        
        // GetTaskInfo
        private static IntPtr _p6;
        private static get_task_info_delegate _d6;
        
        public static int get_task_info(cef_task_manager_t* self, long task_id, CefTaskInfo* info)
        {
            get_task_info_delegate d;
            var p = self->_get_task_info;
            if (p == _p6) { d = _d6; }
            else
            {
                d = (get_task_info_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_task_info_delegate));
                if (_p6 == IntPtr.Zero) { _d6 = d; _p6 = p; }
            }
            return d(self, task_id, info);
        }
        
        // KillTask
        private static IntPtr _p7;
        private static kill_task_delegate _d7;
        
        public static int kill_task(cef_task_manager_t* self, long task_id)
        {
            kill_task_delegate d;
            var p = self->_kill_task;
            if (p == _p7) { d = _d7; }
            else
            {
                d = (kill_task_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(kill_task_delegate));
                if (_p7 == IntPtr.Zero) { _d7 = d; _p7 = p; }
            }
            return d(self, task_id);
        }
        
        // GetTaskIdForBrowserId
        private static IntPtr _p8;
        private static get_task_id_for_browser_id_delegate _d8;
        
        public static long get_task_id_for_browser_id(cef_task_manager_t* self, int browser_id)
        {
            get_task_id_for_browser_id_delegate d;
            var p = self->_get_task_id_for_browser_id;
            if (p == _p8) { d = _d8; }
            else
            {
                d = (get_task_id_for_browser_id_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_task_id_for_browser_id_delegate));
                if (_p8 == IntPtr.Zero) { _d8 = d; _p8 = p; }
            }
            return d(self, browser_id);
        }
        
    }
}
