//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.InteropServices;
    using System.Security;
    
    [StructLayout(LayoutKind.Sequential, Pack = libcef.ALIGN)]
    [SuppressMessage("Microsoft.Design", "CA1049:TypesThatOwnNativeResourcesShouldBeDisposable")]
    internal unsafe struct cef_domevent_t
    {
        internal cef_base_t _base;
        internal IntPtr _get_type;
        internal IntPtr _get_category;
        internal IntPtr _get_phase;
        internal IntPtr _can_bubble;
        internal IntPtr _can_cancel;
        internal IntPtr _get_document;
        internal IntPtr _get_target;
        internal IntPtr _get_current_target;
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void add_ref_delegate(cef_domevent_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int release_delegate(cef_domevent_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int has_one_ref_delegate(cef_domevent_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_string_userfree* get_type_delegate(cef_domevent_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate CefDomEventCategory get_category_delegate(cef_domevent_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate CefDomEventPhase get_phase_delegate(cef_domevent_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int can_bubble_delegate(cef_domevent_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int can_cancel_delegate(cef_domevent_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_domdocument_t* get_document_delegate(cef_domevent_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_domnode_t* get_target_delegate(cef_domevent_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_domnode_t* get_current_target_delegate(cef_domevent_t* self);
        
        // AddRef
        private static IntPtr _p0;
        private static add_ref_delegate _d0;
        
        public static void add_ref(cef_domevent_t* self)
        {
            add_ref_delegate d;
            var p = self->_base._add_ref;
            if (p == _p0) { d = _d0; }
            else
            {
                d = (add_ref_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(add_ref_delegate));
                if (_p0 == IntPtr.Zero) { _d0 = d; _p0 = p; }
            }
            d(self);
        }
        
        // Release
        private static IntPtr _p1;
        private static release_delegate _d1;
        
        public static int release(cef_domevent_t* self)
        {
            release_delegate d;
            var p = self->_base._release;
            if (p == _p1) { d = _d1; }
            else
            {
                d = (release_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(release_delegate));
                if (_p1 == IntPtr.Zero) { _d1 = d; _p1 = p; }
            }
            return d(self);
        }
        
        // HasOneRef
        private static IntPtr _p2;
        private static has_one_ref_delegate _d2;
        
        public static int has_one_ref(cef_domevent_t* self)
        {
            has_one_ref_delegate d;
            var p = self->_base._has_one_ref;
            if (p == _p2) { d = _d2; }
            else
            {
                d = (has_one_ref_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(has_one_ref_delegate));
                if (_p2 == IntPtr.Zero) { _d2 = d; _p2 = p; }
            }
            return d(self);
        }
        
        // GetType
        private static IntPtr _p3;
        private static get_type_delegate _d3;
        
        public static cef_string_userfree* get_type(cef_domevent_t* self)
        {
            get_type_delegate d;
            var p = self->_get_type;
            if (p == _p3) { d = _d3; }
            else
            {
                d = (get_type_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_type_delegate));
                if (_p3 == IntPtr.Zero) { _d3 = d; _p3 = p; }
            }
            return d(self);
        }
        
        // GetCategory
        private static IntPtr _p4;
        private static get_category_delegate _d4;
        
        public static CefDomEventCategory get_category(cef_domevent_t* self)
        {
            get_category_delegate d;
            var p = self->_get_category;
            if (p == _p4) { d = _d4; }
            else
            {
                d = (get_category_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_category_delegate));
                if (_p4 == IntPtr.Zero) { _d4 = d; _p4 = p; }
            }
            return d(self);
        }
        
        // GetPhase
        private static IntPtr _p5;
        private static get_phase_delegate _d5;
        
        public static CefDomEventPhase get_phase(cef_domevent_t* self)
        {
            get_phase_delegate d;
            var p = self->_get_phase;
            if (p == _p5) { d = _d5; }
            else
            {
                d = (get_phase_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_phase_delegate));
                if (_p5 == IntPtr.Zero) { _d5 = d; _p5 = p; }
            }
            return d(self);
        }
        
        // CanBubble
        private static IntPtr _p6;
        private static can_bubble_delegate _d6;
        
        public static int can_bubble(cef_domevent_t* self)
        {
            can_bubble_delegate d;
            var p = self->_can_bubble;
            if (p == _p6) { d = _d6; }
            else
            {
                d = (can_bubble_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(can_bubble_delegate));
                if (_p6 == IntPtr.Zero) { _d6 = d; _p6 = p; }
            }
            return d(self);
        }
        
        // CanCancel
        private static IntPtr _p7;
        private static can_cancel_delegate _d7;
        
        public static int can_cancel(cef_domevent_t* self)
        {
            can_cancel_delegate d;
            var p = self->_can_cancel;
            if (p == _p7) { d = _d7; }
            else
            {
                d = (can_cancel_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(can_cancel_delegate));
                if (_p7 == IntPtr.Zero) { _d7 = d; _p7 = p; }
            }
            return d(self);
        }
        
        // GetDocument
        private static IntPtr _p8;
        private static get_document_delegate _d8;
        
        public static cef_domdocument_t* get_document(cef_domevent_t* self)
        {
            get_document_delegate d;
            var p = self->_get_document;
            if (p == _p8) { d = _d8; }
            else
            {
                d = (get_document_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_document_delegate));
                if (_p8 == IntPtr.Zero) { _d8 = d; _p8 = p; }
            }
            return d(self);
        }
        
        // GetTarget
        private static IntPtr _p9;
        private static get_target_delegate _d9;
        
        public static cef_domnode_t* get_target(cef_domevent_t* self)
        {
            get_target_delegate d;
            var p = self->_get_target;
            if (p == _p9) { d = _d9; }
            else
            {
                d = (get_target_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_target_delegate));
                if (_p9 == IntPtr.Zero) { _d9 = d; _p9 = p; }
            }
            return d(self);
        }
        
        // GetCurrentTarget
        private static IntPtr _pa;
        private static get_current_target_delegate _da;
        
        public static cef_domnode_t* get_current_target(cef_domevent_t* self)
        {
            get_current_target_delegate d;
            var p = self->_get_current_target;
            if (p == _pa) { d = _da; }
            else
            {
                d = (get_current_target_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_current_target_delegate));
                if (_pa == IntPtr.Zero) { _da = d; _pa = p; }
            }
            return d(self);
        }
        
    }
}
