//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "3.3029.1619.geeeb5d7";
        public const int CEF_VERSION_MAJOR = 3;
        public const int CEF_COMMIT_NUMBER = 1619;
        public const string CEF_COMMIT_HASH = "eeeb5d739567e55cb23ba79dc2b71ff2f3450ba1";
        
        public const int CHROME_VERSION_MAJOR = 58;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 3029;
        public const int CHROME_VERSION_PATCH = 81;
        
        public const string CEF_API_HASH_UNIVERSAL = "f0e835273a00acd02a699af272fc8f6ff9c5645c";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "3cf7ac2b9aa61adfb9e5decdf0d32fbf78813355";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "f1d2ed00ab93e03a215fd787e6da9127e2949fd8";
        public const string CEF_API_HASH_PLATFORM_LINUX = "698e69c4297cc63b9893558a8591e7bd7aeeb0d4";
    }
}
