//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "76.1.13+gf19c584+chromium-76.0.3809.132";
        public const int CEF_VERSION_MAJOR = 76;
        public const int CEF_COMMIT_NUMBER = 2037;
        public const string CEF_COMMIT_HASH = "f19c584555e3b78d6877b52e7d10afc356ce77aa";
        
        public const int CHROME_VERSION_MAJOR = 76;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 3809;
        public const int CHROME_VERSION_PATCH = 132;
        
        public const string CEF_API_HASH_UNIVERSAL = "d04fc15ff27c5a8ee71fee4a88383e5c4bbb7b10";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "031426ad8eb80ee32fcf3605837cff8d3bbae3a4";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "47422c9703f7c32013642707b976d299c72f42cb";
        public const string CEF_API_HASH_PLATFORM_LINUX = "d333fdd7eee13c06f58e586513061ce121121e0b";
    }
}
